### ISSUE TITLE
main menu fps capping

### ISSUE THREAD

**Issue by Bangalore1010** [avoitishin/xray-16#11]
Do we have a valid solution to cap main menu/intro video fps (working vsync)? It hurts our graphics cards badly.
I can add to this repo the solution of KD, which i ported to my cop source codes (ECO_RENDER part only):

https://xp-dev.com/sc/change/204486/122

**Comment by avoitishin** [comment]
Does it work for you? I did quick copy paste but haven't seen any results, although i didn't pay too much attention to it as I set VSync in NVIDIA console

**Comment by Bangalore1010** [comment]
It did work for me very well.
I use msi afterburner to cap fps, but it conflicts for example with game booster programs, and i loose the capping. 
I'll commit it, after testing, if you don't mind.

**Comment by avoitishin** [comment]
can you please commit to separate branch and i will merge it into working

**Comment by avoitishin** [comment]
added in 9509d190e52aeb326f2eca1a9b13fa3da72fa125, thanks @Bangalore1010
