### ISSUE TITLE
Ability to download builds

### ISSUE THREAD

**Issue by STALKER2010** [avoitishin/xray-16#12]
Good afternoon!
We need something like nightly builds from master and working branch. For example, every one or two week upload on MEGA. I can do this in main repo (OpenXRay), but not this week - I have no access to fast Windows PC with VS 2013.
And it will be great for others, who want to get latest features, performance improvements and bugfixes.
Thanks.

**Comment by avoitishin** [comment]
Good day,

If you mean uploading compiled binaries - I will not be doing this, but feel free to do it if/when you have time and facilities

Thanks
