### ISSUE TITLE
Fatal error....error

### ISSUE THREAD

**Issue by Swartz27** [avoitishin/xray-16#13]
http://imgur.com/6DlUR1A

This error pops up every once in a while due to changes in the scripts it doesn't like (this one being caused from a new faction added that the game doesn't like I do believe).

The problem isn't the error screen, it's the fact that you can't escape it. If you hit okay, it takes you to the Xray process to close the program, and as soon as you do the error screen pops up again, and the process repeats itself. 
The only way of escaping it is by doing ctrl+alt+del and restarting your PC.

**Comment by avoitishin** [comment]
Yes I am aware of this but since its very rare so I ignored it. Its a byproduct of removing bug trap and I will fix it sometime soon.

**Comment by BeaconDev** [comment]
I'm getting this too, quite frequently actually. Seems like it always gives a stack trace: error too, so I can't even really figure out what's wrong.

**Comment by Swartz27** [comment]
Is it possible we can upgrade the priority on this? With some recent changes I've made the game is no unplayable as this crash happens a lot, and since it leaves no useful error log when it does this I can't troubleshoot.

**Comment by BeaconDev** [comment]
It's definitely the custom binaries, it doesn't happen with the originals. Would be great to get it sorted.

**Comment by avoitishin** [comment]
Do you have steps to reproduce? I didn't get this error in a while

p.s. you can also uncomment //# define USE_BUG_TRAP in xrDebugNew.cpp to get vanilla error handling back if this is really that critical for you

**Comment by revolucas** [comment]
I have no issues with it either and I crash quite frequently. Only rarely does it say "Critical Error" which then you have to open task manager and terminate xrEngine. But even so it is still much faster than having bugtrap enabled and sometimes with bugtrap you can't even open task manager because the screen locks.

**Comment by BeaconDev** [comment]
I can't reproduce it, it's totally random when playing.

The problem for me is not the infinite-looping-ness of it, that's solved by an (annoying, granted) task manager hard close (which I'm very familiar with), it's that the crash just doesn't happen without the custom bins.

**Comment by Highflex** [comment]
BeaconDev, can you describe the situation/scene before crashing? I have been experimenting with the debug binaries, besides being very slow i was able to step through code in visual studio which allowed me to understand some systems much better.

**Comment by BeaconDev** [comment]
Like I said, it's totally random as far as I can tell. I'll do some testing now and see if I can get it to happen again.

**Comment by Highflex** [comment]
Okay, i have been running this branch for some weeks with different mods to check stability, so far Misery/Arsenal and Complete did not crash once on me.

**Comment by avoitishin** [comment]
@Highflex you can step through code with release binaries as well :). If some functions get inlined/optimized you can wrap it with below to temporarily disable optimization:
```c++
#pragma optimize( "", off )
.
.
.
#pragma optimize( "", on )
```

**Comment by Highflex** [comment]
Just tried that out, works good :) thanks for the hint, 

i tend to step through code quite often, as this is a massive codebase it helps understanding some parts.

**Comment by revolucas** [comment]
I think there is confusion here. Whatever is causing your CInifile::r_s16() crash may not be related to the disabled bug trap feature.

**Comment by revolucas** [comment]
Okay, Beacon, I took a look in code of everything that reads from ini using r_s16().

```
m_frags					= file_to_read->r_s16();
m_deaths				= file_to_read->r_s16();
m_spots					= file_to_read->r_s16();
static int goodwill_enemy	= pSettings->r_s16(GAME_RELATIONS_SECT, "goodwill_enemy");
static int goodwill_neutral = pSettings->r_s16(GAME_RELATIONS_SECT, "goodwill_neutal");
static int goodwill_friend	= pSettings->r_s16(GAME_RELATIONS_SECT, "goodwill_friend");
static int attitude_neutral = pSettings->r_s16(GAME_RELATIONS_SECT, "attitude_neutal_threshold");
static int attitude_friend = pSettings->r_s16(GAME_RELATIONS_SECT, "attitude_friend_threshold");
m_iPrefferedFireMode = READ_IF_EXISTS(pSettings, r_s16, section, "preffered_fire_mode", -1);
```

Check your configs to make sure the values for these variables range from −32,768 to 32,767.

**Comment by BeaconDev** [comment]
H Alun,

Thanks for the in-depth response. I've checked through my game_relations.ltx and checked all the values for the variables you noted, and they all seem fine to me, along with a seemingly normal cross table. 'preffered_fire_mode' isn't present in any files in our gamedata, so it must be read from the vanilla file which hasn't been changed.

Here's my game_relations.ltx if you want to take a look, because I can't find anything amiss.

http://puu.sh/eMdRP/05713e80ec.ltx

Regarding the -dbg shortcut, it's not working. http://puu.sh/eMdUB/b3c808f9f8.png

I've also tried altering the Steam launch options and adding '-dbg', but the game .exe doesn't even launch, even though Steam says I'm playing the game for 5 seconds before realising it's not even open.

**Comment by avoitishin** [comment]
Which exe are you trying to start with -dbg?

**Comment by BeaconDev** [comment]
xrEngine.exe shortcut, moved to CoP Root.

**Comment by avoitishin** [comment]
Move it back to bin and create simple start.cmd file in COP root with something like 
```cmd
@echo off
@start bin\xrEngine.exe -dbg -skiplogo
```

**Comment by BeaconDev** [comment]
Thanks, that works when I use Highflex's bins so I guess when I get working bins from Swartz again it'll work with those too.
I'll do some testing and see if I can get more info when I crash with this error next time thanks to -dbg.

**Comment by avoitishin** [comment]
What is wrong with bins Swartz sent you?

One more suggestion I have for you is to stop using legacy IsStalker and company, and start utilizing new engine methods. For example:
```lua
if (obj and obj:is_stalker())   
-- do it   
end
```

**Comment by BeaconDev** [comment]
The crash on start I noted in the issue about 'video card doesn't meet game requirements'.

Thanks for the suggestion, that's not a bad option, but we're not quite ready to totally switch to using modified bins yet and using the new engine methods would mean we'd have to. If Alun can't think of anything else then maybe we'll have to.
