### ISSUE TITLE
Missing MSVCP120.dll error

### ISSUE THREAD

**Issue by BeaconDev** [avoitishin/xray-16#15]
One of the Redux team members is trying to use the latest binaries from this repo, but is getting this error:
http://puu.sh/eciO7/5ad724199f.png

It seems to be related to the C++ redistributable, but he's got the 2013 C++ Visual Studio redistributable installed and it's still happening.

I don't have this problem personally, so I'm not sure what's going on.

He's running Windows 8 x64, just like I am.

**Comment by avoitishin** [comment]
Can he check if he has x86 version if MSVC 2013 redistributable installed?

**Comment by BeaconDev** [comment]
Apparently he only installed the x64, installing the x86 version seems to have fixed that error, but now we have this:

http://puu.sh/eczH3/c6ab6afad2.png

Also, will everyone need to install the x86 MSVC '13 redistributable in the future, or is that temporary?

**Comment by avoitishin** [comment]
This seems like he is trying to start the program using custom shortcut and forgot to set working folder to game root. Basically game is searching for fs game file in bin instead or root

Yes everyone will need this redistributable. Normally such DLLs are installed when you install the game but for mod purposes you can just place it in bin along other engine files.

**Comment by BeaconDev** [comment]
He was running the xrEngine.exe instead of the CoP exe, it's fine now.

Apparently placing the MSVCP120.dll in the bin folder didn't solve his problem earlier, but worst case scenario we can just include the redistributable with the mod. Thanks for the help mate!

**Comment by avoitishin** [comment]
Placing DLL inside bin folder should solve it, I am very surprised to hear that it didn't... Did he place the right version (x86)?

**Comment by BeaconDev** [comment]
Ah, no, it was the x64. Ok, good to know, we can just bundle the .dll :)
