### ISSUE TITLE
DirectX11 not working

### ISSUE THREAD

**Issue by Swartz27** [avoitishin/xray-16#17]
Myself and r_populik cannot get the R4 renderer to function properly. For both of us, promptly on game start it shows an error box saying my video card doesn't meet game requirements.

Neither of us are using modified shaders, as I know that is what normally causes that particular error.

The code in question is identical the code in your working branch.

**Comment by avoitishin** [comment]
Sorry, don't have crystal ball to see what's wrong with your setup... Need more information

**Comment by Swartz27** [comment]
Sorry, I didn't mean to frustrate you.

My setup is 
GTX 970
Intel i5-2500k
8gb RAM
Windows 8.1 64-bit

I believe r_populik's is basically the same, but with a newer processor and Windows 7.

What I should have stated is can you quickly check to see if DX11 works for you. If it does then I know it's a problem on my end and I'll go about fixing it on my own rather than bothering you with it,

**Comment by avoitishin** [comment]
I can run latest build on DX11 with no issues so its probably something's wrong with your system. Was there any log created?

**Comment by Swartz27** [comment]
I didn't think there would be but I just discovered this at the end of the log:

* DVB created: 1536K
* DIB created: 512K
! Renderer doesn't support blender 'effects\shadow_world'
* HWDST/PCF supported and used
! PS:  c:\program files (x86)\steamapps\steamapps\common\stalker call of pripyat\gamedata\shaders\r3\objects\r4\dumb.ps\2048__1__0_____0_____0_____________1___000_00
! D3DReflectShader hr == 0x80004002
! PS:  c:\program files (x86)\steamapps\steamapps\common\stalker call of pripyat\gamedata\shaders\r3\objects\r4\dumb.ps\2048__1__0_____0_____0_____________1___000_00
! D3DReflectShader hr == 0x80004002

I'm going to re-download the repo and see if I get the same error when I make the DX11 dll.

**Comment by avoitishin** [comment]
Try to rename your objects folder to something else and restart the game

**Comment by Swartz27** [comment]
Unfortunately that didn't work.

With this codebase I am supposed to compile the source with the dxguid.lib from the Windows SDK, right?

**Comment by avoitishin** [comment]
That's what @nitrocaster recommended. I personally never had any issues and only replaced it with Windows SDK version when moved to new HD.

**Comment by Swartz27** [comment]
Okay, problem solved. The default Directx sdk directly that VS2013 was looking for was not the June 2010 one for some reason. Although it works fine in DX9-10 with whatever SDK it was using before, without 2010 it has issues in DX11. Manually pointing to the DirectX SDK directory I wanted to use solved the problem (I have 3 different DirectX SDK's installed).

**Comment by BeaconDev** [comment]
This is the same error I've been having, does it mean it's solved in the latest bins?

**Comment by nitrocaster** [comment]
It was fixed with this [patch](https://github.com/OpenXRay/xray-16/commit/dc3a09aadbea62b86e25a67edd5f4725855410b1). If same problem occur to you with current working branch, that means you use wrong dxguid.lib. See [build.txt](https://github.com/OpenXRay/xray-16/blob/master/doc/howto/build.txt).

**Comment by BeaconDev** [comment]
Ok, it may just be because I have really outdated bins, but it's weird because I swear it worked on DX11 before. Maybe I was using DX10, I don't know.
