### ISSUE TITLE
'Your video card doesn't meet game requirements'

### ISSUE THREAD

**Issue by BeaconDev** [avoitishin/xray-16#18]
Just gone back to test the modified bins again and have run into this issue.

When I try to launch the game with the latest binaries, I get this message.

http://puu.sh/ezgSx/bc5dac6770.jpg

I deleted my user.ltx, and the game then launched fine. I reset all my graphics settings again (all max on DX11) and restarted, then the error reappeared.

The error does not happen with vanilla binaries, and the game launches fine.

**Comment by Highflex** [comment]
Can you test my binaries and see if this happens too?

https://dl.dropboxusercontent.com/u/89396767/bin_rel.rar

i forked from avoitishin like 2 days ago. He is just 2 commits ahead and nothing like that should cause this issue.

**Comment by BeaconDev** [comment]
It works with those binaries haha.
Also really neat new splash screen, you've gotta teach me how to alter it, it's something I've wanted to do for a while!

**Comment by BeaconDev** [comment]
In fact, do you have Steam/Skype? It'd be great to be able to chat to you!

**Comment by Highflex** [comment]
Yeah:

http://steamcommunity.com/id/highflex/

feel free to add me

**Comment by avoitishin** [comment]
Beacon when did you build your bins? Try the latest with vsync (same implementation as Highflex)

**Comment by revolucas** [comment]
You can use Resource Hacker on xrEngine.exe to change the bitmap splash logo.

**Comment by avoitishin** [comment]
@BeaconDev confirm whether this can be closed?

**Comment by avoitishin** [comment]
Just reminder for myself: check `ResourceManger_Resources.cpp` line 193. Also check commit 23860b0b2534cea044d4a401d77c6e90a2e5996e in xray-15 for _potential_ fix

**Comment by BeaconDev** [comment]
I didn't build the bins, Jket gave them to me. I wouldn't like to close it as the problem's still happening with the bins from this branch, but I don't have any way to build the latest bins myself. I'll try and get the latest ones from Jket and test again.

**Comment by Swartz27** [comment]
@BeaconDev I believe I used the wrong dxguid.lib while compiling, which is why only DX11 doesn't work and the other modes do.

I'll send you updated binaries soon.

**Comment by BeaconDev** [comment]
Swartz sent me updated binaries, but the game crashes on start using them with an error from gulag-general and smat_terrain.script, so I can't tell if they've fixed the DX11 issue :P

**Comment by avoitishin** [comment]
Look for `local ini_path = "\scripts\\"..work` and delete leading backslash so it reads `"scripts\\"`
