### ISSUE TITLE
Compiling Latest Revision, lua.hpp missing

### ISSUE THREAD

**Issue by Highflex** [avoitishin/xray-16#21]
Hey there,

I noticed that i get a missing lua.hpp when i try to compile your recent revision?

Probably related to luajit-2 i guess.

Errors i get on lua_extensions || luabind :

1>c:\projects\xray_engine\cop_branch\development\xray-16\src\3rd party\lua-extensions\script_additional_libs.h(5): fatal error C1083: Cannot open include file: 'lua.hpp': No such file or directory

How did you make sure that
# include "lua.hpp"

gets found?

**Comment by avoitishin** [comment]
Hey man, haven't seen you for a while, welcome back )

Looks like new luajit-2 directory is missing. Do me a favor, can you follow steps in build instructions? I've added them recently and want to check if they are accurate and complete. Let me know if you still have any issues

**Comment by Highflex** [comment]
Okay thanks for the reply :) will check it out, 

i am quite busy with uni and stuff but still looking forward to do more things with XRAY

**Comment by avoitishin** [comment]
No problem. Specifically looks like you are missing these steps:
- Checkout branch v2.1 into $engine_root$\src\3rd party\luajit-2  
- Start Visual Studio developer command console and navigate to

**Comment by Highflex** [comment]
Your new build instructions are good :), everything works now and i can get back into coding,

thanks again dude :)
