### ISSUE TITLE
Is this fork dead?

### ISSUE THREAD

**Issue by ghost** [avoitishin/xray-16#23]
No updates in a while. Just curious if you're taking a bit of a vacation like Alundaio and Bangalore, or if you're done coding for a while? I check here every day hoping you've done something new, but I realize you have to have a life :P

**Comment by offizierkoma** [comment]
No, it's just TeamEPIC keeping us all down and getting ready for something which is going to destroy our minds with sheer awesomeness.

**Comment by BeaconDev** [comment]
I think he's probably busy with Ray of Hope.

**Comment by offizierkoma** [comment]
Yeah, Ray of Hope has gotten huge recently. Let's just wait, we don't want to divert their attention from important issues. Some patience never hurt anyone.

**Comment by ghost** [comment]
That or maybe Bangalore, Alundaio, and Avo here all joined ISIS or something? LOL

**Comment by offizierkoma** [comment]
Time will tell. LiveLeak too.
