### ISSUE TITLE
Sun direction fix

### ISSUE THREAD

**Issue by avoitishin** [avoitishin/xray-16#6]
Swartz27:
Instead of just the sun direction fix, allow for working sun_altitude and sun_longitude commands. Although the sun direction fix works, it doesn't fully work with Atmosfear 3. The modified dll originally used with Atmosfear 3 enabled usage of those two commands which is how he was able to set the sun and moon direction and longitude. You can see an example of the sun direction fix not working the best as the moon doesn't ever show up with it, due to the lack of those two commands.
To give you a push in the right direction, the fixed dll's he used for this were only the render dll's, so something needs to be corrected there.

**Comment by avoitishin** [comment]
@Swartz27 confirm whether this is still relevant

**Comment by Swartz27** [comment]
It is, but I need to confirm what Cromm said in that it works in DX8 but not other modes. Sorry for taking so long to get around to such a simple task but I will do it soon and get back to you.

I mean, the current system works, it's just not 100% perfect to me as when the sun sets it's not quite where it should be, and I never get to see the moon anymore.

**Comment by Swartz27** [comment]
Proof, DX8, moon shows up in correct location: http://imgur.com/mkWiTfx
DX9-11, moon vanishes: http://imgur.com/gjxlyfW

Conclusion: sun_altitude and sun_longitude only work in DX8. The reason Atmosfear 3 corrects this in R2-R4 binaries is this is where the correction must be made.

**Comment by avoitishin** [comment]
Restored sun movement as defined in weather configs in 6f60d473395c4be6391bae811950226d0bd0ebec. @Swartz27 please confirm

**Comment by Swartz27** [comment]
It works! :D 

You da man.
